# Please becareful modifying this file as some tests may assume
# this file to look a certain way.

icons = true

# Compute file sizes like `du`
[du]
metric = "block"
icons = true
layout = "flat"
level = 1

# Do as `ls -l`
[ls]
icons = true
level = 1
suppress-size = true
long = true
gitignore = true
no_hidden = true

# How many lines of Rust are in this code base?
[rs]
metric = "line"
level = 1
pattern = "\\.rs$"
